server {
    listen 443 ssl; # managed by Certbot
    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    server_name www.treeseek.ca treeseek.ca; # managed by Certbot

    ssl_certificate /etc/letsencrypt/live/treeseek.ca/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/treeseek.ca/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    limit_req_status 429;

    location = /nearest {
        limit_req zone=nearest_limit burst=20 nodelay;

        include proxy_params;
        proxy_pass http://unix:/home/drzewo/webapp/drzewo/drzewo.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/drzewo/webapp/drzewo/drzewo.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name www.treeseek.ca treeseek.ca;

    # Redirect HTTP to HTTPS
    return 301 https://$host$request_uri;
}
